---
language: python
python:
  - "2.7"

bofore_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  - export ANSIBLE_GALAXY=`which ansible-galaxy`
  - sudo $ANSIBLE_GALAXY install smola.java
  - sudo $ANSIBLE_GALAXY install groover.maven
  - sudo $ANSIBLE_GALAXY install kost.virtualbox

script:
  - cat /proc/version
  - cd ansible-playbook

  # Syntax check
  - ansible-playbook -i tests/inventory site.yml --syntax-check

  # First run
  - ansible-playbook -i tests/inventory site.yml --connection=local --sudo

  # Idempotence check
  - ansible-playbook -i tests/inventory site.yml --connection=local --sudo | grep -q 'changed=0.*failed=0'

  # Check installed tools
  - git --version
  - svn --version
  - hg --version
  - java -version
  - ant -version
  - mvn --version
  - vim --version
  - sudo /etc/init.d/vboxdrv setup
  - vboxmanage -version
