---
language: python
python:
  - "2.7"

bofore_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  # Tell Ansible where the roles are
  - printf '[defaults]\nroles_path = ansible-playbook/roles' > ansible.cfg

script:
  # Syntax check
  - ansible-playbook -i ansible-playbook/tests/inventory ansible-playbook/tests/site.yml --syntax-check
  # First run
  - ansible-playbook -i ansible-playbook/tests/inventory ansible-playbook/tests/site.yml --connection=local --sudo
  # Idempotence check
  - >
    ansible-playbook -i ansible-playbook/tests/inventory ansible-playbook/tests/site.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

