---
language: python
python:
  - "2.7"

bofore_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  # Tell Ansible where the roles are
  - printf '[defaults]\nroles_path = ansible-playbook/roles' > ansible.cfg

script:
  # Syntax check
  - ansible-playbook -i ansible-playbook/tests/inventory ansible-playbook/tests/site.yml --syntax-check

  # First run
  - ansible-playbook -i ansible-playbook/tests/inventory ansible-playbook/tests/site.yml --connection=local --sudo

  # Idempotence check
  - >
    ansible-playbook -i ansible-playbook/tests/inventory ansible-playbook/tests/site.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass')
    || (echo 'Idempotence test: fail' && touch failed)

  # Check Git
  - >
    git --version | grep -q "git version" 
    && (echo -e "Git: \e[32mOk\e[39m") || (echo -e "Git: \e[31mfail\e[39m" && touch fail)

  # Check Subversion
  - >
    svn --version | grep -q "svn, version" 
    && (echo -e "Subversion: \e[32mOk\e[39m") || (echo -e "Subversion: \e[31mfail\e[39m" && touch fail)

  # Check Mercurial
  - >
    hg --version | grep -q "Mercurial Distributed SCM" 
    && (echo -e "Mercurial: \e[32mOk\e[39m") || (echo -e "Mercurial: \e[31mfail\e[39m" && touch fail)

  # Check result
  - >
    "ls" -l | grep -q "fail"
    && (echo -e "\e[31mSUCCESS\e[39m" && exit 0) || (echo -e "\e[31mFAIL\e[39m" && exit 1)
