---
language: python
python:
  - "2.7"

bofore_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  - "print '[defaults]n\roles_path = ansible-playbook/roles' > ansible.cfg"
  - cat ansible.cfg

script:
  - ansible-playbook -i ansible-playbook/tests/inventory ansible-playbook/tests/test.yml --syntax-check
