---
language: python
python:
  - "2.7"

bofore_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  # Tell Ansible where the roles are
  - printf '[defaults]\nroles_path = ansible-playbook/roles' > ansible.cfg

script:
  # Syntax check
  - ansible-playbook -i ansible-playbook/tests/inventory ansible-playbook/tests/site.yml --syntax-check
  # First run
  - ansible-playbook -i ansible-playbook/tests/inventory ansible-playbook/tests/site.yml --connection=local --sudo

