---
language: python
python:
  - "2.7"

bofore_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  - export ANSIBLE_GALAXY=`which ansible-galaxy`
  - sudo $ANSIBLE_GALAXY install smola.java
  - sudo $ANSIBLE_GALAXY install groover.maven
  - sudo $ANSIBLE_GALAXY install kost.virtualbox

script:
  - cd ansible-playbook

  # Syntax check
  - ansible-playbook -i tests/inventory site.yml --syntax-check

  # Not running the playbook because the run gets aborted for taking too long.
