#!/usr/bin/env bash

# The script defines a few helper functions and sources the package's installer,
# This way the package installer runs in the context of this script with all the helper functions available to it.

# USE ABSOLUTE PATHS FOR ALL VARIABLES BELOW
# Don't cd back and forth. It's easier to use absolute paths than ensuring we cd back at the end.

# Installers directory (directory of this script)
INSTALLER_DIR=$(dirname "$(readlink -f "$0")")

# Package directory
PACKAGE_DIR="${INSTALLER_DIR}/packages/$1"

# Creates a symbolic link.
# Creates the parent directory if it doesn't exist.
# Removes any existing file or symlink at the destination.
# Removes any existing file or symlink at the destination.
make_symlink() {
    local target="$1"
    local link_name="$2"

    # Use sudo if creating a link outside of $HOME
    if [[ "$link_name" == $HOME/* ]]; then
      sudo_cmd=
    else
      sudo_cmd=sudo
    fi

   # Ensure link path (won't complain if exists)
    $sudo_cmd mkdir -p "${link_name%/*}"

    # Remove any existing file or symlink at the destination
    # Can't use ln -f because the target might be a file not a link.
    $sudo_cmd rm -f "$link_name"

    # Create the symbolic link
    echo "$target - $link_name"
    $sudo_cmd ln -s "$target" "$link_name"
}

# Source the package installer in the context of this script,
# making the helper functions above available in the package installer.
source "${PACKAGE_DIR}/install"