#!/usr/bin/env bash

set -eo pipefail

# Needed to know where to look for additional scripts
SETUP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Remember user details before runnig sudo
# (running sudo changes those)

# Needed to chown new files/directories
USER_NAME=$USER
# Where to create symlinks
USER_HOME="$HOME"
# OS
if [[ -f /etc/redhat-release ]]; then
	OS='redhat'
elif [[ -f /etc/debian_version ]]; then
	OS='debian'
elif [[ $(uname) == 'Darwin' ]]; then
	OS='macos'
else
	echo "Unsupported OS $(uname)"
	exit 1
fi

main() {

    echo "SETUP_HOME=$SETUP_HOME"
    echo "USER_NAME=$USER_NAME"
    echo "USER_HOME=$USER_HOME"
    echo "OS=$OS"

    install_shell

    echo 'Done'

}

install_shell() {
    install_package zsh
    # Change default shell
    change_shell $(which zsh)
    #if [ ! -d "$USERHOME/.oh-my-zsh" ]; then
    #    git clone "https://github.com/robbyrussell/oh-my-zsh.git" "$USERHOME/.oh-my-zsh"
    #fi
    #install_powerline_fonts
    ## install powerlevel9k theme
    #if [ ! -d "$USERHOME/.oh-my-zsh/custom/themes/powerlevel9k" ]; then
    #    git clone "https://github.com/bhilburn/powerlevel9k.git" "$USERHOME/.oh-my-zsh/custom/themes/powerlevel9k"
    #fi
    #chown -R $USERNAME:$USERNAME "$USERHOME/.oh-my-zsh"
    #make_symlink "$SETUP_HOME/home/.zshrc" "$USERHOME/.zshrc"
    #chown $USERNAME:$USERNAME "$USERHOME/.zshrc"
}

change_shell() {
	local new_shell="$1"
	case $OS in
		redhat)
 			#todo: currently requires restart, fix it
			sudo usermod -s "$new_shell" "$USER_NAME"
			;;
		debian)
			sudo chsh -s "$new_shell" $USER_NAME
			;;
		macos)
			# Add the new shell to the accepted list of shells if it's not there yet
			# Without this chsh will fail with 'non-standard shell'
			if ! grep -q $new_shell /etc/shells; then
				# Cannot use sudo together with >>, so appending with tee
				echo $new_shell | sudo tee -a /etc/shells
			fi
			sudo chsh -s $new_shell $USER_NAME
	esac
}

install_package() {
    local packages="$@"
    case $OS in
	    redhat)
		    sudo yum -y install $@
		    ;;
	    ubuntu)
		    sudo apt-get -y install $@
		    ;;
	    macos)
		    brew install $@
		    ;;
    esac
}

main
