# Use Ctrl-a (like in screen) instead of Ctrl-b for prefix
# as Ctrl-b is used for scrolling in some apps
unbind C-b
set -g prefix C-a

# reload tmux config
bind r source-file ~/.config/tmux/tmux.conf

# enable truecolor
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",alacritty:RGB"

# disable delay when pressing ESC
set -s escape-time 0

# enable mouse scrolling
set -g mouse on

# use 1-base window numbering
set -g base-index 1

# show pane header
set -g pane-border-status off

# use vi-style key bindings
set -g status-keys vi
setw -g mode-keys vi

# vi-like select and copy using system clipboard
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "pbcopy"
# mouse select and copy using system clipboard
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"

# Ctrl+Alt+n/p to switch between windows
bind-key -n C-M-n next-window
bind-key -n C-M-p previous-window

# splits
bind-key '\' split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"

# window selector via fzf
bind-key w display-popup -E "sel=\$(tmux list-windows -a -F '#{window_id} #{window_name}' | fzf --with-nth=2..) && tmux switch-client -t \"\${sel%% *}\""

# navigate seamlessly between vim and tmux splits with C-h/j/k/l
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

is_fzf="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?fzf$'"

bind-key -n C-h run "($is_vim && tmux send-keys C-h) || \
                 tmux select-pane -L"

bind-key -n C-j run "($is_vim && tmux send-keys C-j) || \
                 ($is_fzf && tmux send-keys C-j) || \
                 tmux select-pane -D"

bind-key -n C-k run "($is_vim && tmux send-keys C-k) || \
                 ($is_fzf && tmux send-keys C-k) || \
                 tmux select-pane -U"

bind-key -n C-l run "($is_vim && tmux send-keys C-l) || \
                 tmux select-pane -R"

bind-key -n 'C-\' if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

# Status line

# Gruvbox colors
# bg:    #282828
# fg:    #ebdbb2
# aqua:  #689d6a
# green: #98971a
# yellow: #d79921
# orange: #fe8019
# blue:  #458588
# grey:  #504945

# Status bar general settings
set -g status-style "bg=#665c54,fg=#ebdbb2"
set -g status-left ""
set -g status-right ""

# Inactive window buttons
set -g window-status-format "  #W  "

# Active window button (visually distinct)
set -g window-status-current-format "  #W  "
set -g window-status-current-style "bg=#458588,fg=#282828"

# Inactive window style
set -g window-status-style "bg=#504945,fg=#ebdbb2"

# Optional: small gap between window buttons
set -g window-status-separator ""

# Highlight active pane border
set -g pane-active-border-style "fg=#458588"
set -g pane-border-style "fg=#504945"
set -g pane-border-indicators "arrows"
set -g pane-border-status "bottom"
set -g pane-border-format " #P: #{pane_current_command} "
set -g pane-border-lines "heavy"

# OSx-specific config

set -g default-shell $SHELL
set -g default-command "reattach-to-user-namespace -l ${SHELL}"

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
